project:
  type: website

website:
  title: "Yuhang Xu"
  site-url: https://yuhangxyh.github.io/
  #description: "Data"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: papers.qmd
        text: Research
      - href: CV.qmd
        text: CV
        
      - href: teaching.qmd
        text: Teaching
    #  - href: demos.qmd
    #    text: Project Demo
      - href: posts.qmd
        text: Blog
      - icon: rss
        href: posts.xml

     # - about.qmd
    #  - papers.qmd
      #- blog.qmd
  page-footer:
    right: "Â© Copyright 2024 Yuhang Xu | CC-BY-NC 4.0."


format:
  html:
    theme:   
      dark: darkly 
      light: flatly
    
    fontsize: 1.1em
    css: styles.css
    toc: false
  #  link-external-icon: true
    link-external-newwindow: true

editor: visual

execute:
  freeze: auto



